spring.application.name=tenant.reviews
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/property_reviews_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dsc8728$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings for Schema Creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.web.resources.static-locations=classpath:/static/
